__version__ = "1.0.6"
# Copyright 2026 Gregory Howard  all rights reserved.

## ===== ACCOUNT =====
ACCOUNT_ID = "SIM123456"
API_KEY = "YOUR_API_KEY"
REFRESH_TOKEN = "YOUR_REFRESH_TOKEN"
ENABLE_TRADING = True

## ===== SESSION =====
MARKET_OPEN_TIME = "09:30:00"
TRADE_START_TIME = "10:00:00"
STOP_NEW_ENTRIES = "14:30:00"
FORCE_EXIT_TIME = "14:45:00"

## ===== POSITION SIZING =====
POSITIONS = 1.0
ACCOUNT_CAPITAL = 10000

## ===== EMA SETTINGS =====
EMA3_PERIOD = 260
EMA5_PERIOD = 475
EMA20_PERIOD = 1885
EMA_SLOPE_LOOKBACK_SECONDS = 60
EMA20_ADJUSTMENT = 0.0

## ===== NOISE FILTERS =====
NOISE_3_5 = 0.25
NOISE_5_20 = 0.50

## ===== STRIKES =====
STRIKE_STEP = 5
STRIKE_RANGE = 3
CONVERSION_WIDTH = 5

## ===== ENTRY FILTERS =====
MIN_EM = 8.00
MAX_PREMIUM = 200.00
PROFIT_MULTIPLIER = 1.2

## ===== EXECUTION =====
ORDER_TIMEOUT_SECONDS = 180
LOOP_SLEEP_SECONDS = 2

## ===== RETRY =====
ORDER_RETRY_ATTEMPTS = 3
TOKEN_REFRESH_DELAY = 1.0
DATA_RETRY_ATTEMPTS = 3
DATA_RETRY_DELAY = 0.5
MAX_API_FAILURES = 5

## ===== LIMITS =====
MAX_CALLS_ACTIVE = 2
MAX_PUTS_ACTIVE = 2

## ===== SLIPPAGE =====
SLIPPAGE = 0.05

## ===== SPREAD FILTER =====
BID_ASK_SPREAD = 2.00

## ===== PERSISTENCE =====
EMA_MAX_STALENESS_DAYS = 1
EMA_FILE = "ema_state.json"

## ===== FORCE EXIT =====
FORCE_EXIT_ENABLED = True

## ===== SYSTEM MONITORING =====
HEARTBEAT_INTERVAL_SECONDS = 60

## ===== USER ALERTING =====
PUSHOVER_ENABLED = True
PUSHOVER_USER_KEY = "YOUR_USER_KEY"
PUSHOVER_API_TOKEN = "YOUR_API_TOKEN"
WINDOWS_ALERT_ENABLED = True

## ===== ADMIN ALERTING =====
ADMIN_PUSHOVER_ENABLED = True
ADMIN_PUSHOVER_USER_KEY = "uck9cc5jyue5oir91izu2ordr6s4uc"
ADMIN_PUSHOVER_API_TOKEN = "YOUR_ADMIN_API_TOKEN"