# ===== ACCOUNT =====
ACCOUNT_CAPITAL = 10000
ACCOUNT_ID = ""
API_KEY = ""
REFRESH_TOKEN = ""

ENABLE_TRADING = False

PUSHOVER_USER_KEY = ""
PUSHOVER_API_TOKEN = ""

ADMIN_PUSHOVER_USER_KEY = ""
ADMIN_PUSHOVER_API_TOKEN = ""

PUSHOVER_ENABLED = True
WINDOWS_ALERT_ENABLED = True


# ===== ORDERS =====
POSITIONS = 0.05
MIN_EM = 8.0
MAX_PREMIUM = 200.0
PROFIT_MULTIPLIER = 1.2
CONVERSION_WIDTH = 5
SLIPPAGE = 0.05
BID_ASK_SPREAD = 2.0

STRIKE_STEP = 5
STRIKE_RANGE = 3
MAX_CALLS_ACTIVE = 2
MAX_PUTS_ACTIVE = 2


# ===== TIMING =====
MARKET_OPEN_TIME = "09:30:00"
TRADE_START_TIME = "10:00:00"
STOP_NEW_ENTRIES = "14:30:00"
FORCE_EXIT_TIME = "14:45:00"
FORCE_EXIT_ENABLED = True

ORDER_TIMEOUT_SECONDS = 180
LOOP_SLEEP_SECONDS = 2
HEARTBEAT_INTERVAL_SECONDS = 60


# ===== EMA =====
EMA3_SECONDS = 540
EMA5_SECONDS = 900
EMA20_SECONDS = 3600

NOISE_3_5 = 0.25
NOISE_5_20 = 0.50

EMA_SLOPE_LOOKBACK_SECONDS = 60
EMA20_ADJUSTMENT = 0.0
EMA_MAX_STALENESS_DAYS = 1
EMA_FILE = "ema_state.json"


# ===== RETRIES =====
ORDER_RETRY_ATTEMPTS = 3
TOKEN_REFRESH_DELAY = 1.0
DATA_RETRY_ATTEMPTS = 3
DATA_RETRY_DELAY = 0.5
MAX_API_FAILURES = 5
``